.code
	priv r4, r8, r0, 3
	xor r12, r12, r12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 3
	shftli r12, 12
	addi r12, 2166
	shftli r12, 4
	addi r12, 4
	priv r12, r13, r0, 4
	xor r19, r19, r19
	addi r19, 0
	shftli r19, 12
	addi r19, 0
	shftli r19, 12
	addi r19, 0
	shftli r19, 12
	addi r19, 0
	shftli r19, 12
	addi r19, 259
	shftli r19, 4
	addi r19, 4
	mov (r31)(-8), r1
	subi r31, 8
	mov r2, (r31)(0)
	addi r31, 8
